
local function m(XVM)
local __=nil
XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "asd"}},"global")
XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = ""}},"global")
XVM:pushCmd("t_function",{targ = {{type = "string",v = "akdfjadfkjadfjlkdaf"},{type = "string",v = "\n"},{type = "string",v = "한글을 입력해봅니다."},{type = "string",v = "\n"}},name = "대화"},"global")
XVM:pushCmd("t_assign",{id = "이미지.아이디",value = {type = "string",v = "ㅈㅈㅈ"}},"global")
XVM:pushCmd("t_assign",{id = "이미지.파일명",value = {type = "string",v = ""}},"global")
XVM:pushCmd("t_assign",{id = "이미지.위치",value = {type = "string",v = "화면중앙"}},"global")
XVM:pushCmd("t_assign",{id = "이미지.크기",value = {type = "string",v = "원본크기"}},"global")
XVM:pushCmd("t_function",{targ = {},name = "이미지"},"global")
XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "asd"}},"global")
XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = "asd"}},"global")
XVM:pushCmd("t_function",{targ = {{type = "string",v = "asdasd"},{type = "string",v = "\n"},{type = "string",v = "asd"},{type = "string",v = "\n"}},name = "대화"},"global")
XVM:pushCmd("t_assign",{id = "한석이호감도",value = {type = "number",v = 0.0}},"global")
XVM:pushCmd("t_operate",{A = "system.tmp",R = {type = "number",v = 1.0},type = "operate",L = {type = "id",v = "변수"},op = "+"},"global")
XVM:pushCmd("t_assign",{id = "변수",value = {type = "id",v = "system.tmp"}},"global")
XVM:pushCmd("t_function",{targ = {{type = "tag",v = {args = {},name = "=변수"}},{type = "string",v = "\n"},{type = "string",v = "나는 어떻게 할것인가?"},{type = "string",v = "\n"},{type = "tag",v = {args = {"\"북마크1\""},name = "연결"}},{type = "string",v = "집 뒤로 간다"},{type = "tag",v = {args = {},name = "/연결"}},{type = "string",v = "\n"},{type = "tag",v = {args = {"\"북마크2\""},name = "연결"}},{type = "string",v = "집 앞으로 간다"},{type = "tag",v = {args = {},name = "/연결"}},{type = "string",v = "\n"}},name = "독백"},"global")
XVM:pushCmd("t_bookmark",{v = "북마크1"},"global")
XVM:pushCmd("t_operate",{A = "system.tmp",R = {type = "number",v = 100.0},type = "operate",L = {type = "id",v = "한석이호감도"},op = "+"},"global")
XVM:pushCmd("t_assign",{id = "한석이호감도",value = {type = "id",v = "system.tmp"}},"global")
XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "ㅁㄴㅇ"}},"global")
XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = "ㅁㄴㅇ"}},"global")
XVM:pushCmd("t_function",{targ = {{type = "string",v = "집 뒤로 갈까?"},{type = "string",v = "\n"}},name = "대화"},"global")
XVM:pushCmd("t_goto",{v = "선택지끝"},"global")
XVM:pushCmd("t_bookmark",{v = "북마크2"},"global")
XVM:pushCmd("t_operate",{A = "system.tmp",R = {type = "number",v = 100.0},type = "operate",L = {type = "id",v = "한석이호감도"},op = "-"},"global")
XVM:pushCmd("t_assign",{id = "한석이호감도",value = {type = "id",v = "system.tmp"}},"global")
XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "ㅁㄴㅇ"}},"global")
XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = "ㅁㄴㅇ"}},"global")
XVM:pushCmd("t_function",{targ = {{type = "string",v = "집 앞으로 갈까?"},{type = "string",v = "\n"}},name = "대화"},"global")
XVM:pushCmd("t_goto",{v = "선택지끝"},"global")
XVM:pushCmd("t_bookmark",{v = "선택지끝"},"global")
XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "asd"}},"global")
XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = "asd"}},"global")
XVM:pushCmd("t_function",{targ = {{type = "string",v = "난 널 "},{type = "tag",v = {args = {},name = "=한석이호감도"}},{type = "string",v = "만큼 호감해"},{type = "string",v = "\n"}},name = "대화"},"global")
__=function(vm,arg)
	vm:clearFunction("ㅁㄴㅇㅁㄴㅇ")
	XVM:pushCmd("t_assign",{id = "대화.이름",value = {type = "string",v = "ㅁㅇㄴ"}},"ㅁㄴㅇㅁㄴㅇ")
	XVM:pushCmd("t_assign",{id = "대화.표정",value = {type = "string",v = "ㅁㄴㅇ"}},"ㅁㄴㅇㅁㄴㅇ")
	XVM:pushCmd("t_function",{targ = {{type = "string",v = "ㅁㄴㅇㅁㄴㅇ"},{type = "string",v = "\n"},{type = "string",v = "ㅁㄴㅇ"},{type = "string",v = "\n"},{type = "string",v = "ㅁㄴㅇㅁ"},{type = "string",v = "\n"},{type = "string",v = "ㄴㅇㅁㄴㅇ"},{type = "string",v = "\n"}},name = "대화"},"ㅁㄴㅇㅁㄴㅇ")
	
end
XVM:pushCmd("t_registfunc",{name = "ㅁㄴㅇㅁㄴㅇ",func = __,custom = true})
XVM:pushCmd("t_function",{targ = {},name = "ㅁㄴㅇㅁㄴㅇ"},"global")

end
return m
